type AuctionBid @entity(immutable: false) {
  id: ID!
  auctionIndex: BigInt! # uint256
  bidIndex: BigInt! # uint256
  bidder: Bytes! # address
  price: BigInt! # uint256
  amountTomi: BigInt! # uint256
  isClaimed:  Boolean! # bool
  token: Bytes! # address
  blockTimestamp: BigInt!
}

type AuctionBidLimitUpdated @entity(immutable: true) {
  id: Bytes!
  bidLimit: BigInt! # uint256
  blockTimestamp: BigInt!
}

type AuctionCancelBid @entity(immutable: true) {
  id: Bytes!
  auctionIndex: BigInt! # uint256
  bidIndex: BigInt! # uint256
  bidder: Bytes! # address
  blockTimestamp: BigInt!
}

type AuctionClaim @entity(immutable: true) {
  id: Bytes!
  auctionIndex: BigInt! # uint256
  bidIndex: BigInt! # uint256
  bidder: Bytes! # address
  blockTimestamp: BigInt!
}

type AuctionCreated @entity(immutable: true) {
  id: Bytes!
  auctionIndex: BigInt! # uint256
  startTime: BigInt! # uint256
  endTime: BigInt! # uint256
  tokenLimit: BigInt! # uint256
  minBidPrice: BigInt! # uint256
  bidLimit: BigInt! # uint256
  bidCount: BigInt!
  highestBid: BigInt!
  blockTimestamp: BigInt!
}

type AuctionDurationUpdated @entity(immutable: true) {
  id: Bytes!
  duration: BigInt! # uint256
  blockTimestamp: BigInt!
}

type AuctionFundsWalletUpdated @entity(immutable: true) {
  id: Bytes!
  funds: Bytes! # address
  blockTimestamp: BigInt!
}

type AuctionSettled @entity(immutable: true) {
  id: Bytes!
  auctionIndex: BigInt! # uint256
  blockTimestamp: BigInt!
}

type AuctionTeamWalletUpdated @entity(immutable: true) {
  id: Bytes!
  team: Bytes! # address
  blockTimestamp: BigInt!
}

type Initialized @entity(immutable: true) {
  id: Bytes!
  version: Int! # uint8
  blockTimestamp: BigInt!
}

type OwnershipTransferred @entity(immutable: true) {
  id: Bytes!
  previousOwner: Bytes! # address
  newOwner: Bytes! # address
  blockTimestamp: BigInt!
}